export const LOGIN_URL = "/auth/login"
export const REFRESH_TOKEN_URL = "auth/refresh_token"
export const REGISTRATION_URL = "/auth/registration"
export const EXCHANGE_LIST = "/exchange_list"
export const PROFILE = "/profile"
